### ISSUE TITLE
Dramatic from steam 

### ISSUE THREAD

**Issue by TheDynamic7** [xADDBx/Isaac-Online-Modded#3]
[desync_log.txt](https://github.com/user-attachments/files/18049666/desync_log.txt)
[desync_log.txt](https://github.com/user-attachments/files/18049669/desync_log.txt)
these 2 desyncs happened back to back. my friend gave up on troubleshooting and i assume it might have been one of us had debug console enabled while the other didnt. im unsure.

**Comment by xADDBx** [comment]
So both players have only EID installed and both have the EID main.lua modified according to the readme?

**Comment by xADDBx** [comment]
1. Did EID have an update since you edited the main.lua? An update seems to overwrite those changes.
2. Did you modify the correct main.lua? There's on in steamapps/workshop/content; but you need to make sure to edit the one in Steam\steamapps\common\The Binding of Isaac Rebirth\mods\external item descriptions

**Comment by xADDBx** [comment]
Indeed. Remove the old script installation. That could be the cause of the issue.
This tool basically makes normal mods work in coop; so install as normal + the tweaks to the EID main.lua and it should work.
